version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  build_test:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      
      - run:
          name: Install Snyk CLI
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g snyk --unsafe-perm=true --allow-root

      - run:
          name: Configure Snyk
          command: snyk config set
      
      - run:
          name: Install Terraform
          command: |
            curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
            unzip terraform_1.0.0_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            terraform --version
      
      - run:
          name: Validate Terraform
          command: terraform validate
          
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          severity-threshold: high
          token-variable: AUTH_TOKEN
          command: snyk test --all-projects

workflows:
  version: 2
  build-and-test:
    jobs:
      - build_test