version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout

      - run:
          name: Install Snyk CLI
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client
            sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
            sudo apt-get install build-essential python3-dev python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
            pip  install --upgrade pip setuptools==67.7.2
            sudo apt-get install zlib1g-dev libjpeg-dev python3-pythonmagick inkscape xvfb poppler-utils libfile-mimeinfo-perl libimage-exiftool-perl
            sudo apt-get install libmagickwand-dev
            python -m pip install --upgrade pip
            pip install snyk 

      - run:
          name: Install Terraform
          command: |
            curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
            unzip terraform_1.0.0_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            terraform --version

      - run:
          name: Configure Snyk
          command: snyk config set

      - run:
          name: Validate Terraform
          command: terraform validate

      - run:
          name: Run Snyk to scan Terraform files
          command: snyk test --all-projects

workflows:
  version: 2
  build-and-test:
    jobs:
      - build_test
