version: 2.1

executors:
  python39:
    docker:
      - image: circleci/python:3.9

jobs:
  build:
    executor: python39
    
    steps:
      - checkout

      - run:
          name: Install Snyk CLI
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g snyk --unsafe-perm=true --allow-root --prefix /home/circleci/snyk

      - run:
          name: Install Terraform
          command: |
            curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
            unzip terraform_1.0.0_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            terraform --version

      - run:
          name: Configure Snyk
          command: |
            export PATH="$PATH:/home/circleci/snyk/bin"
            snyk config set
      
      - run:
          name: Authenticate Snyk
          command: |
            snyk auth $AUTH_TOKEN
      
      - run:
          name: Validate Terraform
          command: terraform validate

      - run:
          name: Run Snyk to scan Terraform files
          command: snyk test --all-projects

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
